"""Initial Phase 5 Persistence

Revision ID: d0f9abb979f1
Revises: 
Create Date: 2026-08-29 12:26:07.418800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f9abb979f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thermal_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_activity_id', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_mode', sa.String(), nullable=False),
    sa.Column('freshness_state', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('granularity', sa.Integer(), nullable=True),
    sa.Column('coverage_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thermal_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('max_continuous_outdoor_minutes', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_work_order_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('job_lat', sa.Float(), nullable=False),
    sa.Column('job_lng', sa.Float(), nullable=False),
    sa.Column('estimated_outdoor_minutes', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('crew_id', sa.String(), nullable=False),
    sa.Column('crew_lat', sa.Float(), nullable=False),
    sa.Column('crew_lng', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_dispatch_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('thermal_policy_id', sa.String(), nullable=False),
    sa.Column('thermal_policy_version', sa.String(), nullable=False),
    sa.Column('mission_version', sa.Integer(), nullable=False),
    sa.Column('current_decision_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_decision_id'], ['dispatch_decisions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('mission_version', sa.Integer(), nullable=False),
    sa.Column('selected_candidate_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('thermal_evidence_id', sa.String(), nullable=True),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('evaluation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['dispatch_missions.id'], ),
    sa.ForeignKeyConstraint(['thermal_evidence_id'], ['thermal_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('departure_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_minutes', sa.Float(), nullable=False),
    sa.Column('outdoor_minutes', sa.Float(), nullable=False),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_exposure', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('sla_met', sa.Boolean(), nullable=False),
    sa.Column('thermal_policy_met', sa.Boolean(), nullable=True),
    sa.Column('priority_policy_met', sa.Boolean(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('thermal_evidence_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['dispatch_decisions.id'], ),
    sa.ForeignKeyConstraint(['thermal_evidence_id'], ['thermal_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('mission_version', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['dispatch_decisions.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['thermal_evidence.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['dispatch_missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_events')
    op.drop_table('candidate_plans')
    op.drop_table('dispatch_decisions')
    op.drop_table('dispatch_missions')
    op.drop_table('work_orders')
    op.drop_table('thermal_policies')
    op.drop_table('thermal_evidence')
    # ### end Alembic commands ###
