from enum import Enum

class ReasonCode(str, Enum):
    SLA_MET = "SLA_MET"
    SLA_VIOLATION = "SLA_VIOLATION"
    LOWER_CALCULATED_EXPOSURE = "LOWER_CALCULATED_EXPOSURE"
    WITHIN_ALLOWED_DELAY = "WITHIN_ALLOWED_DELAY"
    ALTERNATE_ROUTE_SELECTED = "ALTERNATE_ROUTE_SELECTED"
    THERMAL_POLICY_MET = "THERMAL_POLICY_MET"
    THERMAL_POLICY_CONFLICT = "THERMAL_POLICY_CONFLICT"
    EMERGENCY_PRIORITY = "EMERGENCY_PRIORITY"
    NO_FEASIBLE_CANDIDATE = "NO_FEASIBLE_CANDIDATE"
    NO_POLICY_COMPLIANT_PLAN = "NO_POLICY_COMPLIANT_PLAN"
    SUPERVISOR_APPROVAL_REQUIRED = "SUPERVISOR_APPROVAL_REQUIRED"
    MISSING_REQUIRED_EVIDENCE = "MISSING_REQUIRED_EVIDENCE"
    PRIORITY_POLICY_CONFLICT = "PRIORITY_POLICY_CONFLICT"
    INVALID_CANDIDATE_DATA = "INVALID_CANDIDATE_DATA"
